import { analyzeWithOpenAI } from './providers/openai-review-analyzer.js';
import { confirmPayment, parsePaymentWebhook, paymentCheckoutConfig, updatePaymentSubscription } from './providers/payment/index.js';
import { accessForUser, accessPayload, releaseAnalysisReservation, reserveAnalysis, resultForAccess, usageForAccess } from './access.js';
import { applyPaymentWebhook, paymentToken } from './subscriptions.js';

const encoder = new TextEncoder();
const PBKDF2_ITERATIONS = 100000;
const json = (data, status = 200, headers = {}) => new Response(JSON.stringify(data), { status, headers: { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store', ...headers } });
const error = (message, status = 400, details = {}) => json({ error: message, ...details }, status);
const now = () => new Date().toISOString();
const id = () => crypto.randomUUID();
const cookieMap = (request) => Object.fromEntries((request.headers.get('Cookie') || '').split(';').filter(Boolean).map((item) => item.trim().split('=')));
const bytesToBase64 = (bytes) => btoa(String.fromCharCode(...new Uint8Array(bytes)));
const base64ToBytes = (value) => Uint8Array.from(atob(value), (char) => char.charCodeAt(0));

async function hashPassword(password, salt = crypto.getRandomValues(new Uint8Array(16))) {
  const key = await crypto.subtle.importKey('raw', encoder.encode(password), 'PBKDF2', false, ['deriveBits']);
  const hash = await crypto.subtle.deriveBits({ name: 'PBKDF2', salt, iterations: PBKDF2_ITERATIONS, hash: 'SHA-256' }, key, 256);
  return `${bytesToBase64(salt)}:${bytesToBase64(hash)}`;
}
async function passwordMatches(password, stored) { const [salt, expected] = stored.split(':'); return (await hashPassword(password, base64ToBytes(salt))).split(':')[1] === expected; }
async function readJson(request) { if (Number(request.headers.get('Content-Length') || 0) > 2_000_000) throw new Error('요청이 너무 큽니다.'); return request.json(); }
async function userFor(request, env) { const sid = cookieMap(request).sid; return sid ? env.DB.prepare('SELECT users.id, users.email FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.id=? AND sessions.expires_at>?').bind(sid, Date.now()).first() : null; }
async function balance(env, userId) { return (await env.DB.prepare('SELECT COALESCE(SUM(amount), 0) AS balance FROM credit_ledger WHERE user_id=?').bind(userId).first()).balance; }
const sessionCookie = (sid) => `sid=${sid}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=1209600`;
function maskPii(text) { return String(text).replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi, '[이메일]').replace(/(?:01[0-9][- ]?\d{3,4}[- ]?\d{4})/g, '[전화번호]').replace(/\b\d{6}[- ]?[1-4]\d{6}\b/g, '[주민번호]').replace(/\b(?:\d[ -]?){13,19}\b/g, '[번호]').replace(/(?:서울|부산|대구|인천|광주|대전|울산|세종)[^,.\n]{3,35}/g, '[주소]'); }
function parseCsv(text) { const rows = []; let row = [], value = '', quoted = false; for (let i = 0; i < text.length; i++) { const char = text[i], next = text[i + 1]; if (char === '"' && quoted && next === '"') { value += '"'; i++; } else if (char === '"') quoted = !quoted; else if (char === ',' && !quoted) { row.push(value); value = ''; } else if ((char === '\n' || char === '\r') && !quoted) { if (char === '\r' && next === '\n') i++; row.push(value); if (row.some(Boolean)) rows.push(row); row = []; value = ''; } else value += char; } if (value || row.length) rows.push([...row, value]); if (rows.length < 2) throw new Error('리뷰가 포함된 CSV 파일이 필요합니다.'); const headers = rows.shift().map((item) => item.trim()), commentIndex = headers.indexOf('댓글'); if (commentIndex < 0) throw new Error("CSV에서 '댓글' 항목을 찾을 수 없습니다."); const reviews = rows.map((entry) => maskPii(entry[commentIndex] || '').trim()).filter(Boolean).slice(0, 5000); if (!reviews.length) throw new Error('분석 가능한 댓글이 없습니다.'); return reviews; }
function analyze(reviews) { const themes = [{key:'품질',words:['품질','퀄리티','좋아요','좋습니다','만족','튼튼'],positive:true},{key:'배송',words:['배송','도착','빠르'],positive:true},{key:'포장',words:['포장','선물'],positive:true},{key:'가격',words:['가격','가성비','부담'],positive:true},{key:'디자인',words:['디자인','예쁘'],positive:true},{key:'사이즈',words:['사이즈','작아요','커요'],positive:false},{key:'배송',words:['늦','지연'],positive:false}]; const rank = (positive) => themes.filter((theme) => theme.positive === positive).map((theme) => ({ ...theme, evidence: reviews.filter((review) => theme.words.some((word) => review.includes(word))).slice(0, 3) })).filter((theme) => theme.evidence.length).sort((a, b) => b.evidence.length - a.evidence.length); const strengths = rank(true).slice(0, 3).map((item) => ({ name:item.key,count:item.evidence.length,evidence:item.evidence })), weaknesses = rank(false).slice(0, 3).map((item) => ({ name:item.key,count:item.evidence.length,evidence:item.evidence })), top = strengths[0], counts = new Map(); [...strengths,...weaknesses].forEach((item) => counts.set(item.name, (counts.get(item.name)||0)+item.count)); return { totalReviews:reviews.length, summary:top ? `고객 리뷰에서 ${top.name} 관련 긍정 의견이 가장 많이 확인됐습니다.` : '반복적으로 언급된 고객 의견을 정리했습니다.', strengths, weaknesses, keywords:[...counts].sort((a,b)=>b[1]-a[1]).map(([name,count])=>({name,count})), purchasePoints:strengths.map((item)=>({title:item.name,reason:item.evidence[0]})), copy:[{category:'대표 헤드라인',text:top?`고객이 직접 확인한 ${top.name}, 믿고 선택하세요.`:'고객 리뷰에서 찾은 제품의 강점을 확인하세요.',evidence:top?.evidence||[]},{category:'고객 신뢰 문구',text:top?`실제 고객 리뷰에서 확인된 ${top.name} 만족 경험을 만나보세요.`:'실제 고객 리뷰를 바탕으로 추천합니다.',evidence:top?.evidence||[]},{category:'짧은 강조 문구',text:top?`고객이 남긴 ${top.name} 만족 후기`:'고객 리뷰 기반 추천',evidence:top?.evidence||[]}] }; }
async function validateTurnstile(token, request, env) { if (!env.TURNSTILE_SECRET) return true; if (!token) return false; const form = new FormData(); form.append('secret', env.TURNSTILE_SECRET); form.append('response', token); form.append('remoteip', request.headers.get('CF-Connecting-IP') || ''); const result = await (await fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify', { method:'POST', body:form })).json(); return result.success === true; }
async function grantPaymentCredit(env,payment,providerPaymentId) { if(payment.status==='PAID')return {duplicate:true,credits:await balance(env,payment.user_id)}; try{await env.DB.batch([env.DB.prepare("UPDATE payments SET status='PAID',provider_payment_id=?,credited_at=? WHERE id=? AND status='PENDING'").bind(providerPaymentId,now(),payment.id),env.DB.prepare('INSERT INTO credit_ledger (id,user_id,amount,reason,payment_id,created_at) VALUES (?,?,?,?,?,?)').bind(id(),payment.user_id,payment.credits,'결제 크레딧 지급',payment.id,now())]);return {duplicate:false,credits:await balance(env,payment.user_id)};}catch(err){const latest=await env.DB.prepare('SELECT status FROM payments WHERE id=?').bind(payment.id).first();if(latest?.status==='PAID')return {duplicate:true,credits:await balance(env,payment.user_id)};console.error('PAYMENT_CREDIT_FAILED',err.message);throw new Error('PAYMENT_CREDIT_FAILED');} }
async function api(request, env, pathname) {
  if(request.method==='POST'&&pathname==='/api/webhooks/paddle'){const signatureHeader=request.headers.get('Paddle-Signature')||'';console.log('PADDLE_WEBHOOK_RECEIVED',JSON.stringify({signatureHeaderPresent:Boolean(signatureHeader),hasTimestamp:/(^|;)ts=/.test(signatureHeader),signatureCount:(signatureHeader.match(/(^|;)h1=/g)||[]).length,contentLength:request.headers.get('content-length')||''}));try{const event=await parsePaymentWebhook(request,env);console.log('PADDLE_WEBHOOK_VERIFIED',JSON.stringify({eventId:event.eventId,eventType:event.eventType,paymentId:event.paymentId||'',transactionId:event.providerPaymentId||'',subscriptionId:event.providerSubscriptionId||'',priceId:event.items?.[0]?.priceId||'',billingCycle:event.items?.[0]?.billingCycle??'not-provided'}));const applied=await applyPaymentWebhook(env,event);console.log('PADDLE_WEBHOOK_APPLIED',JSON.stringify({eventId:event.eventId,eventType:event.eventType,result:applied}));return json({ok:true,...applied});}catch(err){console.error('PADDLE_WEBHOOK_REJECTED',JSON.stringify({reason:err.message,signatureHeaderPresent:Boolean(signatureHeader)}));return error('웹훅 검증 또는 구독 처리에 실패했습니다.',401,{code:err.message});}}
  if (request.method === 'GET' && pathname === '/api/config') { const planIds=(await env.DB.prepare("SELECT id FROM plans WHERE active=1 AND id!='free'").all()).results.map((plan)=>plan.id);let paymentReady=planIds.length===3;try{for(const planId of planIds)paymentCheckoutConfig(env,planId);}catch{paymentReady=false;}return json({turnstileSiteKey:env.TURNSTILE_SITE_KEY||'',aiReady:Boolean(env.OPENAI_API_KEY||env.openai_api_key||env.ENVIRONMENT==='test'),paymentReady,paymentMode:env.PADDLE_MODE||'',subscriptionChangeReady:paymentReady&&Boolean(env.PADDLE_API_KEY)}); }
  if (request.method === 'POST' && pathname === '/api/auth/signup') { const {email,password,terms,privacy,turnstileToken} = await readJson(request); if (!/^\S+@\S+\.\S+$/.test(email||'')) return error('올바른 이메일을 입력해주세요.'); if (!password || password.length < 8) return error('비밀번호는 8자 이상이어야 합니다.'); if (!terms || !privacy) return error('이용약관과 개인정보 처리방침 동의가 필요합니다.'); if (!(await validateTurnstile(turnstileToken,request,env))) return error('자동 가입 방지 확인에 실패했습니다.'); const userId=id(),sid=id(),createdAt=now(); try { await env.DB.batch([env.DB.prepare('INSERT INTO users (id,email,password_hash,created_at) VALUES (?,?,?,?)').bind(userId,email.toLowerCase(),await hashPassword(password),createdAt),env.DB.prepare('INSERT INTO sessions (id,user_id,expires_at) VALUES (?,?,?)').bind(sid,userId,Date.now()+1209600000),env.DB.prepare('INSERT INTO subscriptions (user_id,plan_id,status,updated_at) VALUES (?,?,?,?)').bind(userId,'free','ACTIVE',createdAt),env.DB.prepare('INSERT INTO user_consents (user_id,consent_id,version,agreed_at) VALUES (?,?,?,?)').bind(userId,'terms','2026-08-18',createdAt),env.DB.prepare('INSERT INTO user_consents (user_id,consent_id,version,agreed_at) VALUES (?,?,?,?)').bind(userId,'privacy','2026-08-18',createdAt)]); return json({email:email.toLowerCase()},201,{'Set-Cookie':sessionCookie(sid)}); } catch(err) { console.error('SIGNUP_FAILED',err.message); return error('이미 가입된 이메일입니다.',409); } }
  if (request.method === 'POST' && pathname === '/api/auth/login') { const {email,password,turnstileToken}=await readJson(request); if (!(await validateTurnstile(turnstileToken,request,env))) return error('자동 로그인 방지 확인에 실패했습니다.'); const user=await env.DB.prepare('SELECT * FROM users WHERE email=?').bind(String(email||'').toLowerCase()).first(); if(!user || !(await passwordMatches(password||'',user.password_hash))) return error('이메일 또는 비밀번호가 올바르지 않습니다.',401); const sid=id(); await env.DB.prepare('INSERT INTO sessions (id,user_id,expires_at) VALUES (?,?,?)').bind(sid,user.id,Date.now()+1209600000).run(); return json({email:user.email},200,{'Set-Cookie':sessionCookie(sid)}); }
  if (request.method === 'POST' && pathname === '/api/auth/logout') { const sid=cookieMap(request).sid; if(sid) await env.DB.prepare('DELETE FROM sessions WHERE id=?').bind(sid).run(); return json({ok:true},200,{'Set-Cookie':'sid=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0'}); }
  if (request.method === 'GET' && pathname === '/api/me') { const user=await userFor(request,env);if(!user)return json({user:null,access:null});const access=await accessForUser(env,user.id),usage=await usageForAccess(env,user.id,access);return json({user:{email:user.email},access:accessPayload(access,usage)}); }
  if (request.method === 'GET' && pathname === '/api/plans') return json((await env.DB.prepare("SELECT id,name,price,credits AS analysis_limit FROM plans WHERE active=1 ORDER BY CASE id WHEN 'free' THEN 0 WHEN 'starter' THEN 1 WHEN 'growth' THEN 2 WHEN 'pro' THEN 3 ELSE 9 END").all()).results.map((plan)=>({...plan,billing_cycle:plan.id==='free'?'lifetime':'monthly',full_results:plan.id!=='free'})));
  const user=await userFor(request,env); if(!user)return error('로그인이 필요합니다.',401);
  if (request.method === 'POST' && pathname === '/api/analyses') { const {fileName,csv,requestId}=await readJson(request);if(!/^[0-9a-f-]{36}$/i.test(requestId||''))return error('분석 요청 ID가 올바르지 않습니다.');const access=await accessForUser(env,user.id),reviews=parseCsv(csv||'');let reservation;try{reservation=await reserveAnalysis(env,user.id,requestId,access);}catch(err){if(err.message==='PLAN_LIMIT_REACHED'){const usage=await usageForAccess(env,user.id,access);return error('현재 플랜의 분석 한도를 모두 사용했습니다.',402,{code:'PLAN_LIMIT_REACHED',access:accessPayload(access,usage)});}return error('동일한 분석 요청을 처리 중입니다.',409,{code:err.message});}if(reservation.duplicate){if(reservation.status==='COMPLETED'&&reservation.analysis_id){const record=await env.DB.prepare('SELECT id,file_name,review_count,created_at,result_json FROM analyses WHERE id=? AND user_id=?').bind(reservation.analysis_id,user.id).first();if(record){const usage=await usageForAccess(env,user.id,access);return json({...record,result:resultForAccess(JSON.parse(record.result_json),access),locked:!access.fullResults,access:accessPayload(access,usage)});}}return error('동일한 분석 요청을 처리 중입니다.',409,{code:'ANALYSIS_IN_PROGRESS'});}if(!(env.OPENAI_API_KEY||env.openai_api_key||env.ENVIRONMENT==='test')){await releaseAnalysisReservation(env,user.id,requestId);return error('AI 연결이 아직 설정되지 않았습니다.',503);}let result;try{result=env.ENVIRONMENT==='test'?analyze(reviews):await analyzeWithOpenAI(reviews,env);const analysisId=id(),createdAt=now();await env.DB.batch([env.DB.prepare('INSERT INTO analyses (id,user_id,file_name,review_count,result_json,created_at) VALUES (?,?,?,?,?,?)').bind(analysisId,user.id,String(fileName||'reviews.csv').slice(0,200),reviews.length,JSON.stringify(result),createdAt),env.DB.prepare("UPDATE analysis_usage SET analysis_id=?,status='COMPLETED',completed_at=? WHERE id=? AND user_id=? AND status='RESERVED'").bind(analysisId,createdAt,requestId,user.id)]);const usage=await usageForAccess(env,user.id,access);return json({id:analysisId,result:resultForAccess(result,access),locked:!access.fullResults,access:accessPayload(access,usage)},201);}catch(err){await releaseAnalysisReservation(env,user.id,requestId);console.error('AI_ANALYSIS_FAILED',err.message);return error('AI 분석에 실패했습니다. 잠시 후 다시 시도해주세요.',502);} }
  if (request.method === 'GET' && pathname === '/api/analyses') { const access=await accessForUser(env,user.id),records=(await env.DB.prepare('SELECT id,file_name,review_count,created_at,result_json FROM analyses WHERE user_id=? ORDER BY created_at DESC').bind(user.id).all()).results;return json(records.map((record)=>({...record,result:resultForAccess(JSON.parse(record.result_json),access),locked:!access.fullResults}))); }
  if (request.method === 'POST' && pathname === '/api/subscriptions/change') { const {planId}=await readJson(request);if(!['starter','growth','pro'].includes(planId||''))return error('변경할 요금제가 올바르지 않습니다.',400);const subscription=await env.DB.prepare("SELECT * FROM subscriptions WHERE user_id=? AND provider='paddle'").bind(user.id).first();if(!subscription||!['ACTIVE','TRIALING'].includes(String(subscription.status).toUpperCase())||!subscription.provider_subscription_id)return error('변경할 활성 Paddle 구독이 없습니다.',409,{code:'ACTIVE_SUBSCRIPTION_NOT_FOUND'});if(subscription.plan_id===planId)return error('이미 사용 중인 플랜입니다.',409,{code:'PLAN_ALREADY_ACTIVE'});let config;try{config=paymentCheckoutConfig(env,planId);const result=await updatePaymentSubscription(env,{subscriptionId:subscription.provider_subscription_id,priceId:config.priceId,prorationBillingMode:env.PADDLE_PRORATION_BILLING_MODE||'prorated_immediately'});console.log('PADDLE_SUBSCRIPTION_CHANGE_REQUESTED',JSON.stringify({userId:user.id,subscriptionId:subscription.provider_subscription_id,fromPlan:subscription.plan_id,toPlan:planId,prorationBillingMode:result.prorationBillingMode}));return json({ok:true,pending:true,fromPlan:subscription.plan_id,toPlan:planId,prorationBillingMode:result.prorationBillingMode},202);}catch(err){console.error('PADDLE_SUBSCRIPTION_CHANGE_FAILED',JSON.stringify({userId:user.id,fromPlan:subscription.plan_id,toPlan:planId,reason:err.message}));return error('Paddle 플랜 변경 요청에 실패했습니다.',502,{code:err.message});} }
  if (request.method === 'POST' && pathname === '/api/payments/checkout') { const {planId}=await readJson(request);if(planId==='free')return error('FREE 플랜은 결제가 필요하지 않습니다.',400);const currentAccess=await accessForUser(env,user.id);if(currentAccess.fullResults)return error('기존 구독의 플랜 변경은 Paddle 구독 관리에서 처리해야 합니다.',409,{code:'SUBSCRIPTION_CHANGE_REQUIRED'});const plan=await env.DB.prepare("SELECT * FROM plans WHERE id=? AND id!='free' AND active=1").bind(planId).first(); if(!plan)return error('요금제를 찾을 수 없습니다.',404); let config; try{config=paymentCheckoutConfig(env,plan.id);}catch(err){console.error('PAYMENT_CONFIG_FAILED',err.message);return error('결제 기능을 준비 중입니다.',503);} const paymentId=id(); await env.DB.prepare('INSERT INTO payments (id,user_id,plan_id,amount,status,provider,provider_price_id,created_at) VALUES (?,?,?,?,?,?,?,?)').bind(paymentId,user.id,plan.id,plan.price,'PENDING',config.provider,config.priceId||null,now()).run(); if(['toss','paddle'].includes(config.provider))return json({mode:config.provider,paymentId,checkoutUrl:`/payment.html?orderId=${paymentId}`},201); return json({mode:'mock',paymentId,amount:plan.price,planName:plan.name},201); }
  const checkoutMatch=pathname.match(/^\/api\/payments\/checkout\/([A-Za-z0-9_-]{6,64})$/); if(request.method==='GET'&&checkoutMatch){const payment=await env.DB.prepare('SELECT payments.*,plans.name FROM payments JOIN plans ON plans.id=payments.plan_id WHERE payments.id=? AND payments.user_id=?').bind(checkoutMatch[1],user.id).first();if(!payment)return error('결제 정보를 찾을 수 없습니다.',404);if(payment.status!=='PENDING')return error('이미 처리된 결제입니다.',409);let config;try{config=paymentCheckoutConfig(env,payment.plan_id);}catch(err){console.error('PAYMENT_CONFIG_FAILED',err.message);return error('결제 기능을 준비 중입니다.',503);}if(config.provider!==payment.provider)return error('결제 제공업체가 변경되었습니다. 새 결제를 시작해주세요.',409);if(config.provider==='paddle')return json({provider:'paddle',clientToken:config.clientToken,environment:config.mode,priceId:payment.provider_price_id,orderId:payment.id,orderName:`${payment.name} 크레딧`,customerEmail:user.email,paymentToken:await paymentToken(payment,env)});if(config.provider!=='toss')return error('결제 요청이 올바르지 않습니다.',400);const raw=await crypto.subtle.digest('SHA-256',encoder.encode(`${env.SESSION_SECRET}:${user.id}`)),customerKey=bytesToBase64(raw).replace(/[^A-Za-z0-9]/g,'').slice(0,32);return json({provider:'toss',clientKey:config.clientKey,orderId:payment.id,amount:payment.amount,orderName:`${payment.name} 크레딧`,customerKey});}
  if (request.method === 'POST' && pathname === '/api/payments/confirm') { const input=await readJson(request),paymentId=String(input.paymentId||''),payment=await env.DB.prepare('SELECT payments.*,plans.credits FROM payments JOIN plans ON plans.id=payments.plan_id WHERE payments.id=? AND payments.user_id=?').bind(paymentId,user.id).first(); if(!payment)return error('결제 정보를 찾을 수 없습니다.',404); if(payment.status==='PAID')return json({ok:true,credits:await balance(env,user.id),duplicate:true}); if(payment.provider==='paddle')return error('Paddle 결제는 서명된 웹훅으로 확인합니다.',409); let verified;try{verified=await confirmPayment(payment,input,env);}catch(err){console.error('PAYMENT_CONFIRM_FAILED',err.message);return error('결제 승인에 실패했습니다. 결제 내역을 확인해주세요.',502);} try{const granted=await grantPaymentCredit(env,payment,verified.id);return json({ok:true,credits:granted.credits,duplicate:granted.duplicate});}catch{return error('결제는 승인됐지만 크레딧 확인에 실패했습니다. 고객지원에 문의해주세요.',500);} }
  const paymentStatusMatch=pathname.match(/^\/api\/payments\/status\/([A-Za-z0-9_-]{6,64})$/);if(request.method==='GET'&&paymentStatusMatch){const payment=await env.DB.prepare('SELECT status FROM payments WHERE id=? AND user_id=?').bind(paymentStatusMatch[1],user.id).first();if(!payment)return error('결제 정보를 찾을 수 없습니다.',404);const access=await accessForUser(env,user.id),usage=await usageForAccess(env,user.id,access);return json({status:payment.status,access:accessPayload(access,usage)});}
  if(request.method==='GET'&&pathname==='/api/billing'){const access=await accessForUser(env,user.id),usage=await usageForAccess(env,user.id,access);return json({access:accessPayload(access,usage),payments:(await env.DB.prepare('SELECT id,plan_id,amount,status,created_at,billing_period_start,billing_period_end FROM payments WHERE user_id=? ORDER BY created_at DESC').bind(user.id).all()).results});}
  return error('요청을 찾을 수 없습니다.',404);
}
export default { async fetch(request, env) { const url=new URL(request.url); try { return url.pathname.startsWith('/api/') ? await api(request,env,url.pathname) : env.ASSETS.fetch(request); } catch (err) { return error(err.message==='요청이 너무 큽니다.'?err.message:'처리 중 오류가 발생했습니다.',500); } } };
