import { analyzeWithOpenAI } from './providers/openai-review-analyzer.js';

const encoder = new TextEncoder();
const json = (data, status = 200, headers = {}) => new Response(JSON.stringify(data), { status, headers: { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store', ...headers } });
const error = (message, status = 400) => json({ error: message }, status);
const now = () => new Date().toISOString();
const id = () => crypto.randomUUID();
const cookieMap = (request) => Object.fromEntries((request.headers.get('Cookie') || '').split(';').filter(Boolean).map((item) => item.trim().split('=')));
const bytesToBase64 = (bytes) => btoa(String.fromCharCode(...new Uint8Array(bytes)));
const base64ToBytes = (value) => Uint8Array.from(atob(value), (char) => char.charCodeAt(0));

async function hashPassword(password, salt = crypto.getRandomValues(new Uint8Array(16))) {
  const key = await crypto.subtle.importKey('raw', encoder.encode(password), 'PBKDF2', false, ['deriveBits']);
  const hash = await crypto.subtle.deriveBits({ name: 'PBKDF2', salt, iterations: 310000, hash: 'SHA-256' }, key, 256);
  return `${bytesToBase64(salt)}:${bytesToBase64(hash)}`;
}
async function passwordMatches(password, stored) { const [salt, expected] = stored.split(':'); return (await hashPassword(password, base64ToBytes(salt))).split(':')[1] === expected; }
async function readJson(request) { if (Number(request.headers.get('Content-Length') || 0) > 2_000_000) throw new Error('요청이 너무 큽니다.'); return request.json(); }
async function userFor(request, env) { const sid = cookieMap(request).sid; return sid ? env.DB.prepare('SELECT users.id, users.email FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.id=? AND sessions.expires_at>?').bind(sid, Date.now()).first() : null; }
async function balance(env, userId) { return (await env.DB.prepare('SELECT COALESCE(SUM(amount), 0) AS balance FROM credit_ledger WHERE user_id=?').bind(userId).first()).balance; }
const sessionCookie = (sid) => `sid=${sid}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=1209600`;
function maskPii(text) { return String(text).replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi, '[이메일]').replace(/(?:01[0-9][- ]?\d{3,4}[- ]?\d{4})/g, '[전화번호]').replace(/\b\d{6}[- ]?[1-4]\d{6}\b/g, '[주민번호]').replace(/\b(?:\d[ -]?){13,19}\b/g, '[번호]').replace(/(?:서울|부산|대구|인천|광주|대전|울산|세종)[^,.\n]{3,35}/g, '[주소]'); }
function parseCsv(text) { const rows = []; let row = [], value = '', quoted = false; for (let i = 0; i < text.length; i++) { const char = text[i], next = text[i + 1]; if (char === '"' && quoted && next === '"') { value += '"'; i++; } else if (char === '"') quoted = !quoted; else if (char === ',' && !quoted) { row.push(value); value = ''; } else if ((char === '\n' || char === '\r') && !quoted) { if (char === '\r' && next === '\n') i++; row.push(value); if (row.some(Boolean)) rows.push(row); row = []; value = ''; } else value += char; } if (value || row.length) rows.push([...row, value]); if (rows.length < 2) throw new Error('리뷰가 포함된 CSV 파일이 필요합니다.'); const headers = rows.shift().map((item) => item.trim()), commentIndex = headers.indexOf('댓글'); if (commentIndex < 0) throw new Error("CSV에서 '댓글' 항목을 찾을 수 없습니다."); const reviews = rows.map((entry) => maskPii(entry[commentIndex] || '').trim()).filter(Boolean).slice(0, 5000); if (!reviews.length) throw new Error('분석 가능한 댓글이 없습니다.'); return reviews; }
function analyze(reviews) { const themes = [{key:'품질',words:['품질','퀄리티','좋아요','좋습니다','만족','튼튼'],positive:true},{key:'배송',words:['배송','도착','빠르'],positive:true},{key:'포장',words:['포장','선물'],positive:true},{key:'가격',words:['가격','가성비','부담'],positive:true},{key:'디자인',words:['디자인','예쁘'],positive:true},{key:'사이즈',words:['사이즈','작아요','커요'],positive:false},{key:'배송',words:['늦','지연'],positive:false}]; const rank = (positive) => themes.filter((theme) => theme.positive === positive).map((theme) => ({ ...theme, evidence: reviews.filter((review) => theme.words.some((word) => review.includes(word))).slice(0, 3) })).filter((theme) => theme.evidence.length).sort((a, b) => b.evidence.length - a.evidence.length); const strengths = rank(true).slice(0, 3).map((item) => ({ name:item.key,count:item.evidence.length,evidence:item.evidence })), weaknesses = rank(false).slice(0, 3).map((item) => ({ name:item.key,count:item.evidence.length,evidence:item.evidence })), top = strengths[0], counts = new Map(); [...strengths,...weaknesses].forEach((item) => counts.set(item.name, (counts.get(item.name)||0)+item.count)); return { totalReviews:reviews.length, summary:top ? `고객 리뷰에서 ${top.name} 관련 긍정 의견이 가장 많이 확인됐습니다.` : '반복적으로 언급된 고객 의견을 정리했습니다.', strengths, weaknesses, keywords:[...counts].sort((a,b)=>b[1]-a[1]).map(([name,count])=>({name,count})), purchasePoints:strengths.map((item)=>({title:item.name,reason:item.evidence[0]})), copy:[{category:'대표 헤드라인',text:top?`고객이 직접 확인한 ${top.name}, 믿고 선택하세요.`:'고객 리뷰에서 찾은 제품의 강점을 확인하세요.',evidence:top?.evidence||[]},{category:'고객 신뢰 문구',text:top?`실제 고객 리뷰에서 확인된 ${top.name} 만족 경험을 만나보세요.`:'실제 고객 리뷰를 바탕으로 추천합니다.',evidence:top?.evidence||[]},{category:'짧은 강조 문구',text:top?`고객이 남긴 ${top.name} 만족 후기`:'고객 리뷰 기반 추천',evidence:top?.evidence||[]}] }; }
async function validateTurnstile(token, request, env) { if (!env.TURNSTILE_SECRET) return true; if (!token) return false; const form = new FormData(); form.append('secret', env.TURNSTILE_SECRET); form.append('response', token); form.append('remoteip', request.headers.get('CF-Connecting-IP') || ''); const result = await (await fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify', { method:'POST', body:form })).json(); return result.success === true; }
async function verifyPayment(payment, paymentKey, approvalToken, env) { if (env.PAYMENT_PROVIDER === 'mock' && env.ENVIRONMENT === 'development') { if (approvalToken !== 'demo-approved') throw new Error('결제 승인을 확인할 수 없습니다.'); return { id:`mock_${payment.id}`,amount:payment.amount }; } if (env.PAYMENT_PROVIDER !== 'toss' || !env.TOSS_SECRET_KEY || !paymentKey) throw new Error('실결제 설정이 완료되지 않았습니다.'); const auth = btoa(`${env.TOSS_SECRET_KEY}:`), response = await fetch('https://api.tosspayments.com/v1/payments/confirm',{method:'POST',headers:{Authorization:`Basic ${auth}`,'Content-Type':'application/json','Idempotency-Key':payment.id},body:JSON.stringify({paymentKey,orderId:payment.id,amount:payment.amount})}), result = await response.json(); if (!response.ok || result.status !== 'DONE' || result.orderId !== payment.id || result.totalAmount !== payment.amount) throw new Error(result.message || '결제 검증에 실패했습니다.'); return { id:result.paymentKey,amount:result.totalAmount }; }

async function api(request, env, pathname) {
  if (request.method === 'GET' && pathname === '/api/config') return json({ turnstileSiteKey: env.TURNSTILE_SITE_KEY || '', aiReady: Boolean(env.OPENAI_API_KEY) });
  if (request.method === 'POST' && pathname === '/api/auth/signup') { const {email,password,terms,privacy,turnstileToken} = await readJson(request); if (!/^\S+@\S+\.\S+$/.test(email||'')) return error('올바른 이메일을 입력해주세요.'); if (!password || password.length < 8) return error('비밀번호는 8자 이상이어야 합니다.'); if (!terms || !privacy) return error('이용약관과 개인정보 처리방침 동의가 필요합니다.'); if (!(await validateTurnstile(turnstileToken,request,env))) return error('자동 가입 방지 확인에 실패했습니다.'); const userId=id(),sid=id(); try { await env.DB.batch([env.DB.prepare('INSERT INTO users (id,email,password_hash,created_at) VALUES (?,?,?,?)').bind(userId,email.toLowerCase(),await hashPassword(password),now()),env.DB.prepare('INSERT INTO sessions (id,user_id,expires_at) VALUES (?,?,?)').bind(sid,userId,Date.now()+1209600000),env.DB.prepare('INSERT INTO user_consents (user_id,consent_id,version,agreed_at) VALUES (?,?,?,?)').bind(userId,'terms','2026-08-18',now()),env.DB.prepare('INSERT INTO user_consents (user_id,consent_id,version,agreed_at) VALUES (?,?,?,?)').bind(userId,'privacy','2026-08-18',now())]); return json({email:email.toLowerCase()},201,{'Set-Cookie':sessionCookie(sid)}); } catch { return error('이미 가입된 이메일입니다.',409); } }
  if (request.method === 'POST' && pathname === '/api/auth/login') { const {email,password,turnstileToken}=await readJson(request); if (!(await validateTurnstile(turnstileToken,request,env))) return error('자동 로그인 방지 확인에 실패했습니다.'); const user=await env.DB.prepare('SELECT * FROM users WHERE email=?').bind(String(email||'').toLowerCase()).first(); if(!user || !(await passwordMatches(password||'',user.password_hash))) return error('이메일 또는 비밀번호가 올바르지 않습니다.',401); const sid=id(); await env.DB.prepare('INSERT INTO sessions (id,user_id,expires_at) VALUES (?,?,?)').bind(sid,user.id,Date.now()+1209600000).run(); return json({email:user.email},200,{'Set-Cookie':sessionCookie(sid)}); }
  if (request.method === 'POST' && pathname === '/api/auth/logout') { const sid=cookieMap(request).sid; if(sid) await env.DB.prepare('DELETE FROM sessions WHERE id=?').bind(sid).run(); return json({ok:true},200,{'Set-Cookie':'sid=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0'}); }
  if (request.method === 'GET' && pathname === '/api/me') { const user=await userFor(request,env); return json({user:user&&{email:user.email},credits:user?await balance(env,user.id):0}); }
  if (request.method === 'GET' && pathname === '/api/plans') return json((await env.DB.prepare('SELECT id,name,price,credits FROM plans WHERE active=1 ORDER BY price').all()).results);
  const user=await userFor(request,env); if(!user)return error('로그인이 필요합니다.',401);
  if (request.method === 'POST' && pathname === '/api/analyses') { const {fileName,csv}=await readJson(request),reviews=parseCsv(csv||''); if(await balance(env,user.id)<1)return error('분석 크레딧이 부족합니다.',402); if(!env.OPENAI_API_KEY)return error('AI 연결이 아직 설정되지 않았습니다.',503); let result; try{result=await analyzeWithOpenAI(reviews,env);}catch{return error('AI 분석에 실패했습니다. 잠시 후 다시 시도해주세요.',502);} const analysisId=id(); await env.DB.batch([env.DB.prepare('INSERT INTO analyses (id,user_id,file_name,review_count,result_json,created_at) VALUES (?,?,?,?,?,?)').bind(analysisId,user.id,String(fileName||'reviews.csv').slice(0,200),reviews.length,JSON.stringify(result),now()),env.DB.prepare('INSERT INTO credit_ledger (id,user_id,amount,reason,analysis_id,created_at) VALUES (?,?,?,?,?,?)').bind(id(),user.id,-1,'리뷰 분석',analysisId,now())]); return json({id:analysisId,result,credits:await balance(env,user.id)},201); }
  if (request.method === 'GET' && pathname === '/api/analyses') { const records=(await env.DB.prepare('SELECT id,file_name,review_count,created_at,result_json FROM analyses WHERE user_id=? ORDER BY created_at DESC').bind(user.id).all()).results; return json(records.map((x)=>({...x,result:JSON.parse(x.result_json)}))); }
  if (request.method === 'POST' && pathname === '/api/payments/checkout') { const {planId}=await readJson(request),plan=await env.DB.prepare('SELECT * FROM plans WHERE id=? AND active=1').bind(planId).first(); if(!plan)return error('요금제를 찾을 수 없습니다.',404); if(env.PAYMENT_PROVIDER!=='toss' && !(env.PAYMENT_PROVIDER==='mock'&&env.ENVIRONMENT==='development'))return error('결제 기능을 준비 중입니다.',503); const paymentId=id(); await env.DB.prepare('INSERT INTO payments (id,user_id,plan_id,amount,status,created_at) VALUES (?,?,?,?,?,?)').bind(paymentId,user.id,plan.id,plan.price,'PENDING',now()).run(); if(env.PAYMENT_PROVIDER==='toss'){if(!env.TOSS_CLIENT_KEY)return error('결제 설정이 완료되지 않았습니다.',503); const raw=await crypto.subtle.digest('SHA-256',encoder.encode(`${env.SESSION_SECRET}:${user.id}`)),customerKey=bytesToBase64(raw).replace(/[^A-Za-z0-9]/g,'').slice(0,32); return json({mode:'toss',paymentId,amount:plan.price,planName:plan.name,checkoutUrl:`/payment.html?orderId=${paymentId}&amount=${plan.price}&orderName=${encodeURIComponent(`${plan.name} 크레딧`)}&customerKey=${customerKey}&clientKey=${encodeURIComponent(env.TOSS_CLIENT_KEY)}`},201);} return json({mode:'mock',paymentId,amount:plan.price,planName:plan.name},201); }
  if (request.method === 'POST' && pathname === '/api/payments/confirm') { const {paymentId,paymentKey,approvalToken}=await readJson(request),payment=await env.DB.prepare('SELECT payments.*,plans.credits FROM payments JOIN plans ON plans.id=payments.plan_id WHERE payments.id=? AND payments.user_id=?').bind(paymentId,user.id).first(); if(!payment)return error('결제 정보를 찾을 수 없습니다.',404); if(payment.status==='PAID')return json({ok:true,credits:await balance(env,user.id),duplicate:true}); const verified=await verifyPayment(payment,paymentKey,approvalToken,env); try{await env.DB.batch([env.DB.prepare("UPDATE payments SET status='PAID',provider_payment_id=?,credited_at=? WHERE id=? AND status='PENDING'").bind(verified.id,now(),paymentId),env.DB.prepare('INSERT INTO credit_ledger (id,user_id,amount,reason,payment_id,created_at) VALUES (?,?,?,?,?,?)').bind(id(),user.id,payment.credits,'결제 크레딧 지급',paymentId,now())]);}catch{return json({ok:true,credits:await balance(env,user.id),duplicate:true});} return json({ok:true,credits:await balance(env,user.id)}); }
  if(request.method==='GET'&&pathname==='/api/billing')return json({credits:await balance(env,user.id),ledger:(await env.DB.prepare('SELECT amount,reason,created_at FROM credit_ledger WHERE user_id=? ORDER BY created_at DESC').bind(user.id).all()).results,payments:(await env.DB.prepare('SELECT id,amount,status,created_at FROM payments WHERE user_id=? ORDER BY created_at DESC').bind(user.id).all()).results});
  return error('요청을 찾을 수 없습니다.',404);
}
export default { async fetch(request, env) { const url=new URL(request.url); try { return url.pathname.startsWith('/api/') ? await api(request,env,url.pathname) : env.ASSETS.fetch(request); } catch (err) { return error(err.message==='요청이 너무 큽니다.'?err.message:'처리 중 오류가 발생했습니다.',500); } } };
